// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gerencia_saloes_API.Data;

#nullable disable

namespace gerencia_saloes_API.Migrations
{
    [DbContext(typeof(SalaoContext))]
    [Migration("20260127171334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gerencia_saloes_API.Models.Despesa", b =>
                {
                    b.Property<int>("IdDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDespesa"));

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDespesa");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.FechamentoAnual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("QtdConcluidos")
                        .HasColumnType("int");

                    b.Property<int>("QtdNaoCompareceram")
                        .HasColumnType("int");

                    b.Property<int>("QtdPendentes")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FechamentosAnuais");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.FechamentoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("QtdConcluidos")
                        .HasColumnType("int");

                    b.Property<int>("QtdNaoCompareceram")
                        .HasColumnType("int");

                    b.Property<int>("QtdPendentes")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FechamentosDiarios");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.FechamentoMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("QtdConcluidos")
                        .HasColumnType("int");

                    b.Property<int>("QtdNaoCompareceram")
                        .HasColumnType("int");

                    b.Property<int>("QtdPendentes")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FechamentosMensais");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.LucroAnual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFaturamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSalarios")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LucrosAnuais");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.LucroDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFaturamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSalarios")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LucrosDiarios");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.LucroMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("LucroLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFaturamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorSalarios")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LucrosMensais");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.Servico", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServico"));

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("IdTipoServico")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdServico");

                    b.HasIndex("IdTipoServico");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.TipoServico", b =>
                {
                    b.Property<int>("IdTipoServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoServico"));

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorPadrao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTipoServico");

                    b.ToTable("TiposServicos");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("DataExpiracaoToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRecuperacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.Despesa", b =>
                {
                    b.HasOne("gerencia_saloes_API.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("gerencia_saloes_API.Models.Servico", b =>
                {
                    b.HasOne("gerencia_saloes_API.Models.TipoServico", "TipoServico")
                        .WithMany()
                        .HasForeignKey("IdTipoServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServico");
                });
#pragma warning restore 612, 618
        }
    }
}
